/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtamuRouteImport } from './routes/utamu'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as DadazRouteImport } from './routes/dadaz'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DadazIdRouteImport } from './routes/dadaz.$id'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedRedeemRouteImport } from './routes/_authenticated/redeem'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'

const UtamuRoute = UtamuRouteImport.update({
  id: '/utamu',
  path: '/utamu',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DadazRoute = DadazRouteImport.update({
  id: '/dadaz',
  path: '/dadaz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DadazIdRoute = DadazIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DadazRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRedeemRoute = AuthenticatedRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dadaz': typeof DadazRouteWithChildren
  '/groups': typeof GroupsRoute
  '/utamu': typeof UtamuRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/redeem': typeof AuthenticatedRedeemRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/dadaz/$id': typeof DadazIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dadaz': typeof DadazRouteWithChildren
  '/groups': typeof GroupsRoute
  '/utamu': typeof UtamuRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/redeem': typeof AuthenticatedRedeemRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/dadaz/$id': typeof DadazIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dadaz': typeof DadazRouteWithChildren
  '/groups': typeof GroupsRoute
  '/utamu': typeof UtamuRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/redeem': typeof AuthenticatedRedeemRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/dadaz/$id': typeof DadazIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dadaz'
    | '/groups'
    | '/utamu'
    | '/profile'
    | '/redeem'
    | '/wallet'
    | '/dadaz/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dadaz'
    | '/groups'
    | '/utamu'
    | '/profile'
    | '/redeem'
    | '/wallet'
    | '/dadaz/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/dadaz'
    | '/groups'
    | '/utamu'
    | '/_authenticated/profile'
    | '/_authenticated/redeem'
    | '/_authenticated/wallet'
    | '/dadaz/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DadazRoute: typeof DadazRouteWithChildren
  GroupsRoute: typeof GroupsRoute
  UtamuRoute: typeof UtamuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utamu': {
      id: '/utamu'
      path: '/utamu'
      fullPath: '/utamu'
      preLoaderRoute: typeof UtamuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dadaz': {
      id: '/dadaz'
      path: '/dadaz'
      fullPath: '/dadaz'
      preLoaderRoute: typeof DadazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dadaz/$id': {
      id: '/dadaz/$id'
      path: '/$id'
      fullPath: '/dadaz/$id'
      preLoaderRoute: typeof DadazIdRouteImport
      parentRoute: typeof DadazRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redeem': {
      id: '/_authenticated/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof AuthenticatedRedeemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRedeemRoute: typeof AuthenticatedRedeemRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRedeemRoute: AuthenticatedRedeemRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DadazRouteChildren {
  DadazIdRoute: typeof DadazIdRoute
}

const DadazRouteChildren: DadazRouteChildren = {
  DadazIdRoute: DadazIdRoute,
}

const DadazRouteWithChildren = DadazRoute._addFileChildren(DadazRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DadazRoute: DadazRouteWithChildren,
  GroupsRoute: GroupsRoute,
  UtamuRoute: UtamuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
